#!/bin/bash
# ── msolutions ops script — version-controlled in msolutions_custom/deploy/ ──
# Live copy: /opt/scripts/update_tenant_list.sh  (authoritative — the timer runs it).
# This repo copy is kept BYTE-IDENTICAL to the live copy; all infrastructure
# values come from /opt/scripts/deploy.env, never hardcoded here.
# RULE: any change to the live script must be mirrored into deploy/ the SAME DAY
# (see deploy/README.md). Run deploy/check_drift.sh to detect divergence.
# ─────────────────────────────────────────────────────────────────────────────
#
# update_tenant_list.sh - regenerate the nginx tenant lists from the database.
#
# Produces TWO maps and reloads nginx only when either changed:
#   tenants.conf   -> every live tenant subdomain (else nginx returns 404)
#   suspended.conf -> tenants over their storage quota (nginx serves the
#                     "storage limit reached" page instead of the tenant)
#
# Runs every ~2s via odoo-tenant-sync.timer, so suspend/restore is near-instant.
# Infra values come from /opt/scripts/deploy.env (server-only, not in the repo);
# the DB password comes from /opt/scripts/.pgpass (600); role odoo_provision.
set -uo pipefail

[ -r /opt/scripts/deploy.env ] && . /opt/scripts/deploy.env
: "${DB_HOST:?set DB_HOST in deploy.env}"
: "${DB_PORT:=5432}"
: "${CONTROL_DB:?set CONTROL_DB in deploy.env}"
: "${BASE_DOMAIN:?set BASE_DOMAIN in deploy.env}"
: "${NGINX_CONTAINER:?set NGINX_CONTAINER in deploy.env}"
: "${NGINX_CONF_DIR:?set NGINX_CONF_DIR in deploy.env}"
DB_USER="odoo_provision"
TENANTS_FILE="$NGINX_CONF_DIR/tenants.conf"
SUSPENDED_FILE="$NGINX_CONF_DIR/suspended.conf"

export PGPASSFILE="/opt/scripts/.pgpass"
export PGSSLMODE="require"
mkdir -p "$NGINX_CONF_DIR"

# 1) every live tenant database
CLIENTS=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d postgres -tAc \
  "SELECT datname FROM pg_database
   WHERE datname NOT IN ('postgres','template0','template1','$CONTROL_DB')
   AND datistemplate = false ORDER BY datname;") || exit 1

# 2) suspended tenants (over quota) from the control-plane record
SUSPENDED=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$CONTROL_DB" -tAc \
  "SELECT name FROM saas_tenant WHERE suspended = true AND state = 'active' ORDER BY name;") \
  || SUSPENDED=""

TMP_T="$(mktemp)"; TMP_S="$(mktemp)"
{
  echo "# generated by update_tenant_list.sh - do not edit"
  for c in $CLIENTS; do echo "${c}.${BASE_DOMAIN} 1;"; done
  echo "${BASE_DOMAIN} 1;"
  echo "www.${BASE_DOMAIN} 1;"
  # Control-plane host (Odoo web.base.url builds every outbound link on it).
  # Must ALWAYS route -- keep it in the generator so it cannot silently drop.
  echo "${CONTROL_DB}.${BASE_DOMAIN} 1;"
} > "$TMP_T"
{
  echo "# generated by update_tenant_list.sh - do not edit"
  for c in $SUSPENDED; do echo "${c}.${BASE_DOMAIN} 1;"; done
} > "$TMP_S"

changed=0
if ! cmp -s "$TMP_T" "$TENANTS_FILE"; then
    mv "$TMP_T" "$TENANTS_FILE"; chmod 644 "$TENANTS_FILE"; changed=1
else rm -f "$TMP_T"; fi
if ! cmp -s "$TMP_S" "$SUSPENDED_FILE"; then
    mv "$TMP_S" "$SUSPENDED_FILE"; chmod 644 "$SUSPENDED_FILE"; changed=1
else rm -f "$TMP_S"; fi

if [ "$changed" = 1 ]; then
    docker exec "$NGINX_CONTAINER" nginx -s reload 2>/dev/null || true
    echo "tenant lists changed -> nginx reloaded"
fi
